# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u540d\u79f0')),
                ('url', models.URLField(verbose_name='\u6240\u5728\u7f51\u5740')),
                ('source', models.CharField(max_length=128, verbose_name='\u4e0b\u8f7d\u6765\u6e90')),
                ('down_urls', models.TextField(verbose_name='\u4e0b\u8f7d\u5730\u5740,\u591a\u4e2a\u6570\u636ejson)')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
