# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='\u6240\u5728\u7f51\u5740')),
                ('source', models.CharField(max_length=128, verbose_name='\u4e0b\u8f7d\u6765\u6e90')),
                ('down_urls', models.TextField(verbose_name='\u4e0b\u8f7d\u5730\u5740,\u591a\u4e2a\u6570\u636ejson)')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='down_urls',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='source',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bfc\u6f14'),
        ),
        migrations.AddField(
            model_name='movie',
            name='filmtype',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4e3b\u6f14'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='movieres',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie'),
        ),
    ]
