# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160108_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='\u6240\u5728\u7f51\u5740'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
