# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20160109_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='filmscore',
            field=models.FloatField(default=0, verbose_name='\u8bc4\u5206'),
        ),
    ]
